// Wire-shape (PascalCase) fixtures shared by the MSW handlers and the
// schema tests. Shapes mirror the FastAPI DTOs exactly -- if the backend
// contract drifts, the zod parse in the api layer fails loudly here.

export const vehiclesWire = [
  {
    Id: 1,
    AssetNumber: 'PW-001',
    Vin: '1FTFW1E50MFA00001',
    Year: 2021,
    Make: 'Ford',
    Model: 'F-150',
    FuelType: 'Gasoline',
    Status: 'Active',
    Department: 'Public Works',
    AssignedDriver: 'Dana Reyes',
    CurrentMileage: 42000,
    AcquisitionDate: '2021-03-15T00:00:00',
    AcquisitionCost: 38500.0,
    LicensePlate: 'MUN-1001',
    Location: 'Yard A',
    Notes: 'Plow package installed.',
  },
  {
    Id: 2,
    AssetNumber: 'PK-014',
    Vin: '1GCHK23U03F000002',
    Year: 2019,
    Make: 'Chevrolet',
    Model: 'Silverado 2500',
    FuelType: 'Diesel',
    Status: 'InShop',
    Department: 'Parks and Recreation',
    AssignedDriver: null,
    CurrentMileage: 88750,
    AcquisitionDate: '2019-06-01T00:00:00',
    AcquisitionCost: 45200.5,
    LicensePlate: 'MUN-1014',
    Location: 'Central Garage',
    Notes: null,
  },
  {
    Id: 3,
    AssetNumber: 'SN-030',
    Vin: '5YJ3E1EA0LF000003',
    Year: 2023,
    Make: 'Tesla',
    Model: 'Model 3',
    FuelType: 'Electric',
    Status: 'Active',
    Department: 'Sanitation',
    AssignedDriver: 'Lee Osei',
    CurrentMileage: 12040,
    AcquisitionDate: '2023-01-20T00:00:00',
    AcquisitionCost: 41999.99,
    LicensePlate: 'MUN-1030',
    Location: 'Yard B',
    Notes: null,
  },
]

export const fleetSummaryWire = {
  TotalVehicles: 35,
  ByStatus: { Active: 29, InShop: 4, OutOfService: 2 },
  ByFuelType: { Gasoline: 20, Diesel: 12, Electric: 3 },
  ByDepartment: { 'Public Works': 12, 'Parks and Recreation': 9, Sanitation: 14 },
}

export const overdueMaintenanceWire = [
  {
    Id: 11,
    VehicleId: 1,
    VehicleAssetNumber: 'PW-001',
    VehicleDescription: '2021 Ford F-150',
    MaintenanceType: 'OilChange',
    NextDueDate: '2026-06-01T00:00:00',
    NextDueMileage: 41000,
    CurrentMileage: 42000,
    LastCompletedDate: '2026-01-05T00:00:00',
    LastCompletedMileage: 36000,
  },
  {
    Id: 12,
    VehicleId: 2,
    VehicleAssetNumber: 'PK-014',
    VehicleDescription: '2019 Chevrolet Silverado 2500',
    MaintenanceType: 'BrakeInspection',
    NextDueDate: null,
    NextDueMileage: 85000,
    CurrentMileage: 88750,
    LastCompletedDate: null,
    LastCompletedMileage: null,
  },
]

export const upcomingMaintenanceWire = [
  {
    Id: 21,
    VehicleId: 3,
    VehicleAssetNumber: 'SN-030',
    VehicleDescription: '2023 Tesla Model 3',
    MaintenanceType: 'TireRotation',
    NextDueDate: '2026-08-01T00:00:00',
    NextDueMileage: 15000,
    CurrentMileage: 12040,
    LastCompletedDate: null,
    LastCompletedMileage: null,
  },
]

export const maintenanceRecordsWire = [
  {
    Id: 31,
    VehicleId: 1,
    WorkOrderId: 41,
    MaintenanceType: 'OilChange',
    PerformedDate: '2026-01-05T00:00:00',
    MileageAtService: 36000,
    Description: 'Full synthetic oil change',
    Cost: 89.95,
    TechnicianName: 'M. Alvarez',
  },
  {
    Id: 32,
    VehicleId: 1,
    WorkOrderId: null,
    MaintenanceType: 'TireRotation',
    PerformedDate: '2025-10-12T00:00:00',
    MileageAtService: 31000,
    Description: 'Rotate + balance',
    Cost: 40.0,
    TechnicianName: 'M. Alvarez',
  },
]

export const workOrdersWire = [
  {
    Id: 41,
    WorkOrderNumber: 'WO-2026-00019',
    VehicleId: 1,
    Status: 'InProgress',
    Priority: 'Critical',
    Description: 'Hydraulic lift cylinder failure',
    RequestedDate: '2026-06-20T00:00:00',
    CompletedDate: null,
    AssignedTechnician: 'R. Chen',
    LaborHours: null,
    TotalCost: null,
    Notes: 'Parts on order.',
  },
  {
    Id: 42,
    WorkOrderNumber: 'WO-2026-00023',
    VehicleId: 2,
    Status: 'Completed',
    Priority: 'Medium',
    Description: 'Replace serpentine belt',
    RequestedDate: '2026-05-02T00:00:00',
    CompletedDate: '2026-05-04T00:00:00',
    AssignedTechnician: null,
    LaborHours: 2.5,
    TotalCost: 312.4,
    Notes: null,
  },
]
